Repository GSG-G11/e-store, pull requests merged in 2022-04, with the labels that each got.

#10 Create file structure
  .eslintrc.json
  .gitignore
  .vscode/settings.json
  __test__/db.test.js
  __test__/routes.test.js
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/App.jsx
  client/src/index.css
  client/src/index.js
  example.env
  package-lock.json
  package.json
  server/app.js
  server/controllers/index.js
  server/database/config/build/build.js
  server/database/config/build/fakeData.sql
  server/database/config/build/init.sql
  server/database/config/connections.js
  server/database/queries/index.js
  server/index.js
  server/routes/index.js
  server/utils/error/CustomErr.js
  server/utils/error/index.js
  server/utils/index.js
  server/utils/validtion/index.js
Labels: Done

#11 Setup the server
  package-lock.json
  package.json
  server/app.js
  server/index.js
  server/routes/index.js
Labels: approved

#13 Add fake tests
  .eslintrc.json
  __test__/db.test.js
  __test__/routes.test.js
Labels: approved

#14 database setup
  server/database/config/build/fakeData.sql
  server/database/config/build/init.sql
  server/database/config/connections.js
Labels: Awaiting Review

#15 5 handle error
  server/controllers/error/clientError.js
  server/controllers/error/index.js
  server/controllers/error/serverError.js
  server/controllers/index.js
  server/routes/index.js
  server/utils/error/CustomErr.js
  server/utils/error/index.js
  server/utils/index.js
Labels: Awaiting Review

#16 handle products vaildation schema
  server/utils/index.js
  server/utils/validtion/index.js
  server/utils/validtion/productsSchema.js
Labels: Awaiting Review

#19 handle add product endpoint
  server/controllers/index.js
  server/controllers/products/addProduct.js
  server/controllers/products/index.js
  server/database/queries/index.js
  server/database/queries/products/addProduct.js
  server/database/queries/products/index.js
  server/routes/index.js
  server/utils/validtion/productsSchema.js
Labels: Awaiting Review

#20 get all products
  server/controllers/index.js
  server/controllers/products/getProducts.js
  server/controllers/products/index.js
  server/database/queries/index.js
  server/database/queries/products/getProductsQuery.js
  server/database/queries/products/index.js
  server/routes/index.js
Labels: Awaiting Review

#21 8 handle edit product
  server/controllers/error/serverError.js
  server/controllers/index.js
  server/controllers/products/editProduct.js
  server/controllers/products/index.js
  server/database/queries/index.js
  server/database/queries/products/editProduct.js
  server/database/queries/products/index.js
  server/routes/index.js
Labels: Awaiting Review

#22 get specific product
  server/controllers/index.js
  server/controllers/products/getProduct.js
  server/controllers/products/index.js
  server/database/queries/index.js
  server/database/queries/products/getProductQuery.js
  server/database/queries/products/index.js
  server/routes/index.js
Labels: approved

#25 9 delete product
  server/controllers/index.js
  server/controllers/products/deleteProduct.js
  server/controllers/products/index.js
  server/database/queries/index.js
  server/database/queries/products/deleteProduct.js
  server/database/queries/products/index.js
  server/routes/index.js
Labels: approved

#38 add generic button
  client/src/components/generic/Button.css
  client/src/components/generic/Button.js
Labels: Awaiting Review

#40 create Input component
  client/src/components/generic/Input.css
  client/src/components/generic/Input.jsx
Labels: approved

#41 add generic icon
  client/src/components/generic/Icon.css
  client/src/components/generic/Icon.js
Labels: Awaiting Review

#43 create navbar
  client/public/index.html
  client/src/App.jsx
  client/src/components/Navbar/Navbar.css
  client/src/components/Navbar/Navbar.jsx
  client/src/components/Navbar/index.js
  client/src/components/generic/Button.css
  client/src/components/generic/Button.js
  client/src/components/generic/Icon.js
  client/src/components/generic/Input.css
  client/src/components/generic/index.js
  client/src/components/index.js
  client/src/images/logo.png
  client/src/index.css
  package.json
  server/app.js
  server/database/config/build/build.js
  server/database/queries/index.js
  server/routes/index.js
Labels: Awaiting Review

#44 30 create=login component
  client/src/components/generic/Input.css
  client/src/components/generic/Input.jsx
  client/src/components/generic/Title.jsx
  client/src/components/login/Login.css
  client/src/components/login/Login.jsx
Labels: Awaiting Review

#46 create info component
  client/src/App.jsx
  client/src/components/Info/Info.css
  client/src/components/Info/Info.jsx
  client/src/components/Info/index.js
  client/src/components/Navbar/Navbar.css
  client/src/components/index.js
  client/src/components/login/Login.jsx
  client/src/components/login/index.js
Labels: Awaiting Review

#47 Cart-component
  client/src/components/cart/Cart.css
  client/src/components/cart/Cart.js
Labels: Awaiting Review

#48 select component
  client/src/components/generic/Select.css
  client/src/components/generic/Select.jsx
Labels: Awaiting Review

#49 homepage
  client/src/App.jsx
  client/src/components/Home/Home.css
  client/src/components/Home/Home.jsx
  client/src/components/Home/index.js
  client/src/components/Info/Info.css
  client/src/components/Navbar/Navbar.css
  client/src/components/Navbar/Navbar.jsx
  client/src/components/ProductCard/ProductCard.css
  client/src/components/ProductCard/ProductCard.jsx
  client/src/components/ProductCard/index.js
  client/src/components/generic/Select.css
  client/src/components/generic/Select.jsx
  client/src/components/generic/Title.jsx
  client/src/components/generic/index.js
  client/src/components/index.js
  client/src/components/login/Login.css
  package-lock.json
  package.json
Labels: Awaiting Review

#55 handle add to cart function
  client/src/App.jsx
  client/src/components/ProductCard/ProductCard.jsx
  client/src/components/cart/Cart.js
Labels: Awaiting Review

#57 handle remove and decrment cart functions
  client/src/App.jsx
  client/src/components/Navbar/Navbar.css
  client/src/components/Navbar/Navbar.jsx
  client/src/components/cart/Cart.css
  client/src/components/cart/Cart.js
  client/src/components/login/Login.css
  client/src/components/login/Login.jsx
Labels: Awaiting Review

#58 create loader
  .vscode/settings.json
  client/src/App.jsx
  client/src/components/Home/Home.jsx
  client/src/components/Loader/Loader.css
  client/src/components/Loader/Loader.jsx
  client/src/components/Loader/index.js
  client/src/components/cart/Cart.css
  client/src/components/login/Login.css
Labels: Awaiting Review

#59 31 creat add product form component
  client/src/App.jsx
  client/src/components/addForm/AddForm.css
  client/src/components/addForm/AddForm.jsx
  client/src/components/addForm/index.js
  client/src/components/index.js
  client/src/components/login/Login.css
Labels: Awaiting Review

#61 handle login and logout
  client/src/App.jsx
  client/src/components/Navbar/Navbar.jsx
  client/src/components/generic/Input.jsx
  client/src/components/login/Login.jsx
Labels: approved

#63 render delete and edit icons
  client/src/App.jsx
  client/src/components/Home/Home.jsx
  client/src/components/Navbar/Navbar.jsx
  client/src/components/ProductCard/ProductCard.css
  client/src/components/ProductCard/ProductCard.jsx
  client/src/components/cart/Cart.css
  client/src/components/cart/Cart.js
Labels: Awaiting Review

#64 52 search product
  client/src/App.jsx
  client/src/components/Home/Home.jsx
  client/src/components/Navbar/Navbar.jsx
  client/src/components/ProductCard/ProductCard.jsx
Labels: Awaiting Review

#65 add new product
  client/src/App.jsx
  client/src/components/Home/Home.jsx
  client/src/components/addForm/AddForm.css
  client/src/components/addForm/AddForm.jsx
  server/controllers/products/addProduct.js
Labels: approved

#26 test routes
  __test__/routes.test.js
  server/controllers/error/serverError.js
Labels: Awaiting Review

#72 delete product functionality and confirm component
  client/src/components/confirmation/Confirmation.css
  client/src/components/confirmation/Confirmation.jsx
  client/src/components/confirmation/index.js
  client/src/components/index.js
Labels: Awaiting Review

#73 edit product
  client/src/App.jsx
  client/src/components/Home/Home.jsx
  client/src/components/ProductCard/ProductCard.jsx
  client/src/components/addForm/AddForm.jsx
  client/src/components/generic/Select.jsx
  server/controllers/products/editProduct.js
  server/database/queries/products/editProduct.js
Labels: Awaiting Review

#74 delete product
  client/src/App.jsx
  client/src/components/Home/Home.jsx
  client/src/components/ProductCard/ProductCard.jsx
  client/src/components/confirmation/Confirmation.jsx
Labels: Awaiting Review

#76 filter product
  client/src/App.jsx
  client/src/components/Home/Home.jsx
  client/src/components/generic/Select.jsx
Labels: Awaiting Review

#77 67 delete product
  client/src/App.jsx
  client/src/components/Home/Home.jsx
  client/src/components/Product/Product.jsx
  client/src/components/ProductCard/ProductCard.jsx
  client/src/components/ProductDetails/ProductDetails.jsx
  client/src/components/confirmation/Confirmation.jsx
Labels: Awaiting Review

#75 not found page component
  client/src/App.jsx
  client/src/components/Home/Home.css
  client/src/components/Home/Home.jsx
  client/src/components/Product/Product.jsx
  client/src/components/ProductCard/ProductCard.css
  client/src/components/addForm/AddForm.css
  client/src/components/cart/index.js
  client/src/components/confirmation/Confirmation.css
  client/src/components/index.js
  client/src/components/login/Login.css
  client/src/components/login/Login.jsx
  client/src/components/ُُError/Err.css
  client/src/components/ُُError/Err.jsx
  client/src/components/ُُError/index.js
Labels: In Progress

#79 add notifcation for add to cart and remove from cart
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Loader/Loader.css
  client/src/components/ProductDetails/ProductDetails.jsx
Labels: approved

#81 Test database
  .vscode/settings.json
  __test__/db.test.js
  package.json
Labels: approved
